import os

cmds = [
    'python yolov9_bytetrack_pth_4_cropping.py --save_cropped_humans D:/tmp/3.1/demo_videos_2_output/possession_change2/save_cropped --video_path D:/tmp/3.1/demo_videos_2/possession_change2 --use_json --output_dir D:/tmp/3.1/demo_videos_2_output/possession_change2/output --save_asset -m D:/tmp/3.1/best.pt --court_image E:/0220/videocut/court.jpg --show_video -o D:/tmp/3.1/demo_videos_2_output/possession_change2/output_video.mp4 --stop_at -1 --use_saved_box',
    'python yolov9_bytetrack_pth_4_cropping.py --save_cropped_humans D:/tmp/3.1/demo_videos_2_output/possession_change1/save_cropped --video_path D:/tmp/3.1/demo_videos_2/possession_change1 --use_json --output_dir D:/tmp/3.1/demo_videos_2_output/possession_change1/output --save_asset -m D:/tmp/3.1/best.pt --court_image E:/0220/videocut/court.jpg --show_video -o D:/tmp/3.1/demo_videos_2_output/possession_change1/output_video.mp4 --stop_at -1 --use_saved_box',
    'python yolov9_bytetrack_pth_4_cropping.py --save_cropped_humans D:/tmp/3.1/demo_videos_2_output/lack_pressure/save_cropped --video_path D:/tmp/3.1/demo_videos_2/lack_pressure --use_json --output_dir D:/tmp/3.1/demo_videos_2_output/lack_pressure/output --save_asset -m D:/tmp/3.1/best.pt --court_image E:/0220/videocut/court.jpg --show_video -o D:/tmp/3.1/demo_videos_2_output/lack_pressure/output_video.mp4 --stop_at -1 --use_saved_box',
    'python yolov9_bytetrack_pth_4_cropping.py --save_cropped_humans D:/tmp/3.1/demo_videos_2_output/goalkeeper_poor_position/save_cropped --video_path D:/tmp/3.1/demo_videos_2/goalkeeper_poor_position --use_json --output_dir D:/tmp/3.1/demo_videos_2_output/goalkeeper_poor_position/output --save_asset -m D:/tmp/3.1/best.pt --court_image E:/0220/videocut/court.jpg --show_video -o D:/tmp/3.1/demo_videos_2_output/goalkeeper_poor_position/output_video.mp4 --stop_at -1 --use_saved_box',
    'python yolov9_bytetrack_pth_4_cropping.py --save_cropped_humans D:/tmp/3.1/demo_videos_2_output/2990_long/save_cropped --video_path D:/tmp/3.1/demo_videos_2/2990_long --use_json --output_dir D:/tmp/3.1/demo_videos_2_output/2990_long/output --save_asset -m D:/tmp/3.1/best.pt --court_image E:/0220/videocut/court.jpg --show_video -o D:/tmp/3.1/demo_videos_2_output/2990_long/output_video.mp4 --stop_at -1 --use_saved_box',
    'python yolov9_bytetrack_pth_4_cropping.py --save_cropped_humans D:/tmp/3.1/demo_videos_2_output/1100_long/save_cropped --video_path D:/tmp/3.1/demo_videos_2/1100_long --use_json --output_dir D:/tmp/3.1/demo_videos_2_output/1100_long/output --save_asset -m D:/tmp/3.1/best.pt --court_image E:/0220/videocut/court.jpg --show_video -o D:/tmp/3.1/demo_videos_2_output/1100_long/output_video.mp4 --stop_at -1 --use_saved_box',
    
    'python yolov9_bytetrack_pth_4_cropping.py --save_cropped_humans D:/tmp/3.1/demo_videos_output/ball_out_of_range1/save_cropped --video_path D:/tmp/3.1/demo_videos/ball_out_of_range1 --use_json --output_dir D:/tmp/3.1/demo_videos_output/ball_out_of_range1/output --save_asset -m D:/tmp/3.1/best.pt --court_image E:/0220/videocut/court.jpg --show_video -o D:/tmp/3.1/demo_videos_output/ball_out_of_range1/output_video.mp4 --stop_at -1 --use_saved_box',
    'python yolov9_bytetrack_pth_4_cropping.py --save_cropped_humans D:/tmp/3.1/demo_videos_output/ball_out_of_range2/save_cropped --video_path D:/tmp/3.1/demo_videos/ball_out_of_range2 --use_json --output_dir D:/tmp/3.1/demo_videos_output/ball_out_of_range2/output --save_asset -m D:/tmp/3.1/best.pt --court_image E:/0220/videocut/court.jpg --show_video -o D:/tmp/3.1/demo_videos_output/ball_out_of_range2/output_video.mp4 --stop_at -1 --use_saved_box',
    'python yolov9_bytetrack_pth_4_cropping.py --save_cropped_humans D:/tmp/3.1/demo_videos_output/reverse/save_cropped --video_path D:/tmp/3.1/demo_videos/reverse --use_json --output_dir D:/tmp/3.1/demo_videos_output/reverse/output --save_asset -m D:/tmp/3.1/best.pt --court_image E:/0220/videocut/court.jpg --show_video -o D:/tmp/3.1/demo_videos_output/reverse/output_video.mp4 --stop_at -1 --use_saved_box',
    'python yolov9_bytetrack_pth_4_cropping.py --save_cropped_humans D:/tmp/3.1/demo_videos_output/lack_pressure/save_cropped --video_path D:/tmp/3.1/demo_videos/lack_pressure --use_json --output_dir D:/tmp/3.1/demo_videos_output/lack_pressure/output --save_asset -m D:/tmp/3.1/best.pt --court_image E:/0220/videocut/court.jpg --show_video -o D:/tmp/3.1/demo_videos_output/lack_pressure/output_video.mp4 --stop_at -1 --use_saved_box',
    'python yolov9_bytetrack_pth_4_cropping.py --save_cropped_humans D:/tmp/3.1/demo_videos_output/commit_foul/save_cropped --video_path D:/tmp/3.1/demo_videos/commit_foul --use_json --output_dir D:/tmp/3.1/demo_videos_output/commit_foul/output --save_asset -m D:/tmp/3.1/best.pt --court_image E:/0220/videocut/court.jpg --show_video -o D:/tmp/3.1/demo_videos_output/commit_foul/output_video.mp4 --stop_at -1 --use_saved_box',
    'python yolov9_bytetrack_pth_4_cropping.py --save_cropped_humans D:/tmp/3.1/demo_videos_output/goalkeeper_GKEM/save_cropped --video_path D:/tmp/3.1/demo_videos/goalkeeper_GKEM --use_json --output_dir D:/tmp/3.1/demo_videos_output/goalkeeper_GKEM/output --save_asset -m D:/tmp/3.1/best.pt --court_image E:/0220/videocut/court.jpg --show_video -o D:/tmp/3.1/demo_videos_output/goalkeeper_GKEM/output_video.mp4 --stop_at -1 --use_saved_box',
    'python yolov9_bytetrack_pth_4_cropping.py --save_cropped_humans D:/tmp/3.1/demo_videos_output/lowSpeed1/save_cropped --video_path D:/tmp/3.1/demo_videos/lowSpeed1 --use_json --output_dir D:/tmp/3.1/demo_videos_output/lowSpeed1/output --save_asset -m D:/tmp/3.1/best.pt --court_image E:/0220/videocut/court.jpg --show_video -o D:/tmp/3.1/demo_videos_output/lowSpeed1/output_video.mp4 --stop_at -1 --use_saved_box',
    'python yolov9_bytetrack_pth_4_cropping.py --save_cropped_humans D:/tmp/3.1/demo_videos_output/delay_restart/save_cropped --video_path D:/tmp/3.1/demo_videos/delay_restart --use_json --output_dir D:/tmp/3.1/demo_videos_output/delay_restart/output --save_asset -m D:/tmp/3.1/best.pt --court_image E:/0220/videocut/court.jpg --show_video -o D:/tmp/3.1/demo_videos_output/delay_restart/output_video.mp4 --stop_at -1 --use_saved_box',

]

for cmd in cmds:
    os.system(cmd)