# docker-compose.yml
version: "3.8"

services:
  football_player_analysis:
    build:
      context: .  # Directory containing the Dockerfile
      dockerfile: Dockerfile  # Name of your Dockerfile
    container_name: football_player_analysis
    restart: unless-stopped
    runtime: nvidia  # Use NVIDIA runtime for GPU support
    shm_size: '32g'  # Set shared memory size to 64GB
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Make all GPUs visible to the container
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM_PLUGIN_PATH=/opt/conda/lib/python3.8/site-packages/cv2/qt/plugins
      - QT_QPA_PLATFORM=xcb
    devices:
      - "/dev/ttyS3:/dev/ttyS3"  # Map the host COM port to the container (adjust ttyS3 as needed)
    volumes:
      - .:/whole  # Mount the local code directory
      - /tmp/.X11-unix:/tmp/.X11-unix  # Mount the X11 socket for GUI
      - /home/hkuit/john/icac_web/media:/whole/media
    stdin_open: true  # Equivalent to `-i` to keep STDIN open
    tty: true  # Allocate a pseudo-TTY
